### ISSUE TITLE
use pseudorandom number generators (PRNGs) ?

### ISSUE THREAD

**Issue by tissatussa** [redsalmon91/FoxSEE#5]
i see you provide a link to Xorshiro128** at http://prng.di.unimi.it .. this is about "pseudorandom number generators" (PRNGs) .. why do you use these ?  Just curious ..

**Comment by buildingwheels** [comment]
Sorry about the late reply.. I just saw this issue now.
PRNG is used generate random numbers for zobrist hashing.
