### ISSUE TITLE
Logo proposal

### ISSUE THREAD

**Issue by PabloDaniel0** [redsalmon91/FoxSEE#7]
I have designed a logo for FoxSee, and I would like to propose it as the official logo of the engine, the images used are copyright free.
![FoxSee_logo](https://user-images.githubusercontent.com/82627806/161197635-96c3f02b-f03e-41f1-8783-bb0379ce7127.png)
![FoxSee_logo_100x50](https://user-images.githubusercontent.com/82627806/161197648-4b3a1a79-c0ab-423d-857c-715a5f2773d7.jpg)
![In Arena](https://user-images.githubusercontent.com/82627806/161197874-c616137f-a027-467b-ab34-a763008a2250.png)

**Comment by buildingwheels** [comment]
hi Pablo, thanks for making the LOGO, it looks great! May I ask the title to be changed to "FoxSEE" instead of "Fox See"? Because "SEE" also refers to Static-Exchange-Evaluation which was the algorithm intrigued me to make this engine :)

**Comment by PabloDaniel0** [comment]
![FoxSee_logo](https://user-images.githubusercontent.com/82627806/162546868-f3889cd7-2dd6-4e03-9d0a-e32ffda7a5f8.jpg)
updated version of the logo, it changes a little but it is the same style.

**Comment by buildingwheels** [comment]
hi Pablo, thank you! I am planning to put it in my repo and credit you on the main page. What do you think?

**Comment by PabloDaniel0** [comment]
I like the idea

**Comment by buildingwheels** [comment]
hi @PabloDaniel0, I have updated the repo to include this logo, and credits section in the README. Thank you!
