### ISSUE TITLE
Release version 8.0.0 binary removed or will it be recompiled?

### ISSUE THREAD

**Issue by rwbc** [redsalmon91/FoxSEE#8]
Downloaded the compilation some hours ago, as it was already 'announced' yesterday.
What happened with it? It's still visible in the release 'tags' though, but source only at the time of writing this.

**Comment by buildingwheels** [comment]
hi @rwbc , thanks for paying attention to FoxSEE. I had an incorrect hash setting in my customized testing, caused a false 60% win rate vs. v7.35. After the release, I realized the settings problem and deleted v8 release. I am on travel right now, won't be able to redo a full test run until July. I put it on hold for now.
