### ISSUE TITLE
v8.0.0 loses on time

### ISSUE THREAD

**Issue by tissatussa** [redsalmon91/FoxSEE#9]
i successfully compiled your v8.0.0 source into a Linux binary, but it loses on time in CuteChess : see my settings .. it happens with other engines also : just before the time control (40th move) the engine uses too much time and loses the game.
[ i'm on Xubuntu 21.10 and CuteChess v1.2.0 =newest ]

---

![FoxSEE_v8-0-0_lost_on_time_1](https://user-images.githubusercontent.com/1109281/169788704-28f99adf-89d5-4b2d-afb8-3af9edbab3f0.png)

---

![FoxSEE_v8-0-0_lost_on_time_2](https://user-images.githubusercontent.com/1109281/169788726-8c06bc85-d11c-462c-bfde-30246732b1c6.png)

**Comment by buildingwheels** [comment]
Thanks @tissatussa, I have removed v8.0 version since its testing setup was incorrect.
